
```{r 3: Make a scatterplot of bill_depth_mm vs. bill_length_mm. That is, make a scatterplot with bill_depth_mm on the y-axis and bill_length_mm on the x-axis. Describe the relationship between these two variablesm}

ggplot(pngs,
    # aesthetic on the global level, passed down to all subsequent geom layers
    mapping = aes(x = bill_length_mm, 
                  y = bill_depth_mm)) +
    # geometrical object that representa the data
    # each geom function can have own aesthetics
    # aesthetic mappings at the local level
    geom_point(mapping = aes(color = species,  
                             shape = species)) + 
    # new geometric object based on a linear model
    geom_smooth(method = "lm") +
    labs(
        title = "Bill length and Bill depth",
        subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
        x = "Bill length (mm)", 
        y = "Bill depth (mm)",
        color = "Species", 
        shape = "Species") +
    scale_color_colorblind()
```

```{r 4: What happens if you make a scatterplot of species vs. bill_depth_mm? What might be a better choice of geom?}
ggplot(
    data = pngs,
    # aesthetic on the global level, passed down to all subsequent geom layers
    mapping = aes(x = species, 
                  y = bill_depth_mm)) +
    # geometrical object that representa the data
    # each geom function can have own aesthetics
    # aesthetic mappings at the local level
    # geom_col(mapping = aes(color = species))\
    geom_point()

# Species is a categorical variable and a scatterplot of a categorical variable is not that useful 
```

```{r 5: Why does the following give an error and how would you fix it?}
ggplot(data = penguins) + 
  geom_point()
# no aesthetic mappings are provided
```

```{r 6: What does the na.rm argument do in geom_point()? What is the default value of the argument? Create a scatterplot where you successfully use this argument set to TRUE}
ggplot(data = penguins,
       aes(x = bill_depth_mm, y = bill_length_mm)) + 
    # Add the following caption to the plot you made in the previous exercise: Hint: Take a look at the documentation for labs()
    labs(title = "Data comes from the palmerpenguins package.") +
    # default is FALSE <- 
    geom_point(na.rm = TRUE)


```

```{r 7: Add the following caption to the plot you made in the previous exercise: Hint: Take a look at the documentation for labs()}
ggplot(data = penguins,
       aes(x = bill_depth_mm, y = bill_length_mm)) + 
    labs(title = "Data comes from the palmerpenguins package.") +
    # default is FALSE
    geom_point(na.rm = TRUE)
```

```{r 8: Recreate the following visualization. What aesthetic should bill_depth_mm be mapped to? And should it be mapped at the global level or at the geom level?}
ggplot(
    data = pngs,
    mapping = aes(
        x = flipper_length_mm, 
        y = body_mass_g)) +
    geom_point(aes(color = bill_depth_mm)) +
    geom_smooth()
```

