```{r slice_ methods}
flights |> 
    group_by(month) |> 
    slice_max(dep_delay) |> 
    relocate(dep_delay) |> 
    arrange(desc(dep_delay))
```

```{r}
flights |> 
    group_by(year, month, day) |>
    summarise(n = n()) |> 
    summarise(mean = mean(month))

flights |> 
    group_by(year, month, day) |>
    summarise(n = n(),
              .groups = "drop") |> 
    summarise(mean = mean(month))
```

```{r}
flights |> 
    summarise(mean = mean(dep_delay,
                          na.rm = TRUE),
              .by = month)
```

```{r Which carrier has the worst average delays? Challenge: can you disentangle the effects of bad airports vs. bad carriers? Why/why not? (Hint: think about flights |> group_by(carrier, dest) |> summarize(n()))}

flights |> 
    group_by(carrier, dest) |> 
    summarise(delay = mean(arr_delay,
                           na.rm = TRUE)) |>
    slice_max(delay,
              n = 1) |> 
    arrange(desc(delay))


flights |> 
    dplyr::filter(carrier == "B6") |> 
    group_by(dest) |> 
    summarize(amount = n()) |> 
    slice_max(order_by = amount,
              n = 1) |> 
    arrange(desc(amount))
```

```{r Find the flights that are most delayed upon departure from each destination}
flights |> 
    group_by(dest) |> 
    arrange(dest, desc(dep_delay)) |> 
    slice_head(n = 5) |> 
    select(dest, dep_delay)

flights |> 
    group_by(dest) |> 
    arrange(dest, desc(dep_delay)) |> 
    slice_max(order_by = dep_delay,
              n = 5) |> 
    select(dest, dep_delay)
```

```{r How do delays vary over the course of the day. Illustrate your answer with a plot.}
flights |> 
    group_by(hour) |>
    summarise(mean_delay = mean(dep_delay, na.rm = TRUE)) |> 
    ggplot(aes(x = hour, y = mean_delay)) +
    geom_point() +
    geom_smooth()
```

```{r What happens if you supply a negative n to slice_min() and friends?}
# negative number arranges the df in ascending 
flights |> 
    slice_min(dep_delay,
              n = 5) |> 
    relocate(dep_delay)

flights |> 
    slice_min(dep_delay,
              n = -5) |> 
    relocate(dep_delay)

flights |> 
  slice_max(dep_delay, 
            n = -5) |>
  relocate(dep_delay)

flights |> 
  slice_max(dep_delay, 
            n = 5) |>
  relocate(dep_delay)
```


```{r Explain what count() does in terms of the dplyr verbs you just learned. What does the sort argument to count() do?}
flights |> 
    count(month, flight,
          sort = TRUE) |> 
    group_by(month) |> 
    slice_max(order_by = n,
              n = 2)

flights |> 
    dplyr::filter(month == 6 & flight == 15) |> 
    count(flight)
```

```{r Suppose we have the following tiny data frame}
df <- tibble(
  x = 1:5,
  y = c("a", "b", "a", "a", "b"),
  z = c("K", "K", "L", "L", "K")
)

# will not be the same df but a tibbel with two groups for a and b
df |>
  group_by(y)



# Write down what you think the output will look like, then check if you were correct, and describe what arrange() does. Also comment on how it’s different from the group_by() in part (a)?

# aaabb, will not group only arrange and change row order
df |>
  arrange(y)


# Write down what you think the output will look like, then check if you were correct, and describe what the pipeline does.
df |>
  group_by(y) |>
  summarize(mean_x = mean(x))


df |>
  group_by(y, z) |>
  summarize(mean_x = mean(x))

df |>
  group_by(y, z) |>
  mutate(mean_x = mean(x))

# the df will not have a grouping anymore
df |>
  group_by(y, z) |>
  summarize(mean_x = mean(x), .groups = "drop")
```

