


```{r}
students <- read_csv("https://pos.it/r4ds-students-csv", na = c("N/A", ""))

# change names and remove spaces
renamed_students <- students |> 
    rename(
        student_id = `Student ID`,
        full_name = `Full Name`
    )

# or
janitor_students <- janitor::clean_names(students) |> 
    mutate(meal_plan = factor(meal_plan),
           age = parse_number(if_else(age == "five", "5", age)))

# will skip 2 first lines
read_csv(
  "The first line of metadata
  The second line of metadata
  x,y,z
  1,2,3",
  skip = 2
)

# will drop the lines beginning with the # or the comments
read_csv(
  "# A comment I want to skip
  x,y,z
  1,2,3",
  comment = "#",
  col_names = TRUE
  # col_names = c("a", "b")
)

read_csv(
  "1,2,3
  4,5,6",
  col_names = FALSE
)

read_csv(
  "1,2,3
  4,5,6",
  col_names = TRUE
)
```

```{r}
mtcars_spec_cols <- read_csv(file = "mtcars.csv",
                             col_types = cols_only(hp = col_integer(),
                                                   am = col_integer(),
                                                   vs = col_factor(levels = c("1", "0"), 
                                                                   include_na = FALSE)))
```

```{r}
folder <- "~/github/RfDS/"

# writing csv and rds files for loading and writing comparison k
write_csv(mtcars, paste(folder, "mtcars_two_csv.csv", sep = "/"))
write_csv(mtcars_spec_cols, paste(folder, "mtcars_spec_cols_csv.csv", sep = "/"))
write_rds(mtcars, paste(folder, "mtcars_two_rds.rds", sep = "/"))
write_rds(mtcars_spec_cols, paste(folder, "mtcars_spec_cols_rds.rds", sep = "/"))


listed_files <- list.files(folder, 
                      pattern = "*.rds|*.csv")

listed_files_otherregex <- list.files(folder, 
                      pattern = "\\.rds$|\\.csv$")

# using simple regex
for (i in 1:length(listed_files)) {
    assign(listed_files[i],
           read_csv(paste(folder, listed_files[i], sep ='/')))
}
# using complex regex
for (i in 1:length(listed_files_otherregex)) {
    assign(listed_files_otherregex[i],
           read_csv(paste(folder, listed_files_otherregex[i], sep ='/')))
}
```


```{r}
message_on_top <- " NEF NÄHE DATTELN
2024-2271 in 34 km EntfernungNichts gewählt
Bitte geben Sie an, ob Sie Interesse haben oder nicht.
ABLEHNEN INTERESSE 
NotarztDatum: 25/06/2024
Beginn: 08:00 UhrDauer:
24 h 0 minEnde:
08:00 Uhr
Honorar: 45 €/h
Voraussetzungen:ANGESTELLTENVERHÄLTNIS ODER PRAXISNIEDERLASSUNG NACH § 23C SGB IVMAX 24 STUNDEN AM STÜCKMASERN-IMPFSCHUTZ GEMÄSS GESETZBearbeiter: Celine Hassel

```

