```{r}
```

```{r}
mpg |> 
    ggplot(aes(x = displ, y = hwy, color = class)) +
    geom_point()

mpg |> 
    ggplot(aes(x = displ, y = hwy, shape = class)) +
    geom_point()

mpg |> 
    ggplot(aes(x = displ, y = hwy, size = class)) +
    geom_point()

mpg |> 
    ggplot(aes(x = displ, y = hwy, alpha = class)) +
    geom_point()

mpg |> 
    ggplot(aes(x = displ, y = hwy)) +
    geom_point(color = "red",
               shape = 2)

```

```{r}
ggplot(mtcars, aes(x = cyl, y = qsec, color = am)) +
    geom_point() +
    geom_smooth(aes(linetype = as.character(am)))
```

```{r}
# will do smooth on all points
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point(aes(color = class)) + 
  geom_smooth()

# will do smooth for every class!!!
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth(aes(color = class))

# will do smooth for every class!!!
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point(aes(color = class)) + 
  geom_smooth()

# will do smooth for every class!!!
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth(aes(color = class == c("minivan")))
```


```{r}
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_point(
    data = mpg |> dplyr::filter(class == "2seater"), 
    color = "red") +
  geom_point(
    data = mpg |> dplyr::filter(class == "2seater"), 
    shape = "circle open", size = 3, color = "red")
```

```{r}
ggplot(mpg, aes(x = hwy)) +
    geom_histogram(binwidth = 2)

ggplot(mpg, aes(x = hwy)) +
    geom_density()

ggplot(mpg, aes(x = hwy)) +
    geom_boxplot()

```

Facets
```{r}
ggplot(mpg, aes(x = displ, y = hwy)) + 
  geom_point() + 
  facet_grid(drv ~ cyl)
```

