---
title: "Explore"
output: html_document
---
```{r}
# na.rm not a method. It's an argument, not working 
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Explore section

```{r}
library(tidyverse)
library(palmerpenguins)
library(ggthemes)
```

```{r}
pngs <- palmerpenguins::penguins
glimpse(pngs)
```

```{r}
# starting with the first ggplot layer similar to a canvas
ggplot(
    data = pngs,
    # aesthetic on the global level, passed down to all subsequent geom layers
    mapping = aes(x = flipper_length_mm, 
                  y = body_mass_g)) +
    # geometrical object that representa the data
    # each geom function can have own aesthetics
    # aesthetic mappings at the local level
    geom_point(mapping = aes(color = species, 
                             shape = species)) + 
    # new geometric object based on a linear model
    geom_smooth(method = "lm") +
    labs(
        title = "Body mass and flipper length",
        subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
        x = "Flipper length (mm)", 
        y = "Body mass (g)",
        color = "Species", 
        shape = "Species") +
    scale_color_colorblind()
```

## 1.4 Visualizing distributions
### 1.4.1 A categorical variable

```{r}
ggplot(pngs, 
       aes(x = fct_infreq(species))) +
    geom_bar()
```

## 1.4.2 A numerical variable

```{r}
ggplot(pngs,
       aes(x = body_mass_g)) +
    # depending on the scale of the x axis
    geom_histogram(binwidth = 20)
```

```{r}
# density plot
ggplot(pngs, 
       aes(x = body_mass_g)) +
    # smoothed out version of the histogram
    geom_density()
```

# 1.5 Visualizing relationships
## 1.5.1 A numerical and a categorical variable

```{r}
ggplot(pngs,
       aes(x = species,
           y = body_mass_g)) +
    geom_boxplot()
```

```{r}
ggplot(pngs, 
       aes(x = body_mass_g, fill = species, color = species)) + 
    geom_density(alpha = 0.5)
```

# 1.5.2 Two categorical variables

```{r Stacked bar plots for two categorical relationsships}
ggplot(pngs,
       aes(x = island, fill = species)) +
    geom_bar()
```

```{r}
# relative frequency plot created by setting position = "fill" in the geom
ggplot(pngs, 
        aes(x = island, fill = species)) +
    geom_bar(position = "fill")
```

# 1.5.4 Three or more variables

```{r}
ggplot(pngs, 
       aes(x = flipper_length_mm,
           y = body_mass_g)) +
    # shape as third variable for creating shapes
    geom_point(aes(color = species, shape = island)) +
    # variable should be categori
    facet_wrap(~island)
```

